# Generated by Django 5.2.15 on 2026-06-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TRP", "گزارش آزمون کارکردی"),
                            ("VTR", "گزارش آزمون آسیب\u200cپذیری"),
                        ],
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "klass_title",
                    models.CharField(max_length=255, verbose_name="عنوان کلاس"),
                ),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "guidance",
                    models.TextField(blank=True, verbose_name="راهنمای ارزیاب"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "ordering": ["framework", "order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Clause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="شرح الزام")),
                ("objective", models.TextField(blank=True, verbose_name="هدف الزام")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="frameworks.requirement",
                    ),
                ),
            ],
            options={
                "ordering": ["requirement", "order", "code"],
            },
        ),
        migrations.CreateModel(
            name="DefaultTextTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "قبول"),
                            ("finding", "عدم انطباق"),
                            ("not_applicable", "مصداق ندارد"),
                        ],
                        max_length=16,
                    ),
                ),
                ("template", models.TextField(verbose_name="قالب متن")),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_texts",
                        to="frameworks.framework",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("framework", "status"), name="uniq_template_per_status"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("framework", "code"), name="uniq_requirement_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="clause",
            constraint=models.UniqueConstraint(
                fields=("requirement", "code"), name="uniq_clause_code"
            ),
        ),
    ]
