# Generated by Django 5.2.15 on 2026-06-12 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن بند")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_clauses",
                        to="frameworks.clause",
                    ),
                ),
            ],
            options={
                "ordering": ["clause", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clause", "order"), name="uniq_subclause_order"
                    )
                ],
            },
        ),
    ]
