# Generated by Django 5.2.15 on 2026-06-10 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="نام شرکت"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام انگلیسی"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام سامانه")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=64, verbose_name="نسخه"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="systems",
                        to="catalog.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name", "version"),
                        name="uniq_system_per_company",
                    )
                ],
            },
        ),
    ]
