# Generated by Django 5.2.15 on 2026-06-10 20:55

import apps.assessments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("frameworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TRP", "گزارش آزمون کارکردی"),
                            ("VTR", "گزارش آزمون آسیب\u200cپذیری"),
                        ],
                        editable=False,
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under_assessment", "در حال ارزیابی"),
                            ("under_review", "در حال بازبینی"),
                            ("completed", "تکمیل\u200cشده"),
                        ],
                        default="under_assessment",
                        max_length=24,
                    ),
                ),
                (
                    "tester_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="کد آزمونگر"
                    ),
                ),
                (
                    "approver_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="کد تأییدکننده"
                    ),
                ),
                (
                    "test_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ اتمام آزمون"
                    ),
                ),
                (
                    "architecture_overview",
                    models.TextField(blank=True, verbose_name="نمای کلی معماری"),
                ),
                (
                    "test_configuration",
                    models.TextField(blank=True, verbose_name="پیکربندی آزمون"),
                ),
                (
                    "doc_version",
                    models.CharField(
                        default="1.0", max_length=16, verbose_name="نسخه سند"
                    ),
                ),
                ("change_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="frameworks.framework",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="catalog.productsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=apps.assessments.models.attachment_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=128)),
                ("size", models.PositiveBigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ClauseAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "بررسی\u200cنشده"),
                            ("compliant", "قبول"),
                            ("finding", "عدم انطباق"),
                            ("not_applicable", "مصداق ندارد"),
                        ],
                        default="unreviewed",
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("text_edited", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clause_assessments",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="frameworks.clause",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["clause__requirement__order", "clause__order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment", "clause"),
                        name="uniq_clause_per_assessment",
                    )
                ],
            },
        ),
    ]
