# Generated by Django 5.2.15 on 2026-06-12 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("frameworks", "0002_subclause"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubClauseAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "بررسی\u200cنشده"),
                            ("compliant", "قبول"),
                            ("finding", "عدم انطباق"),
                            ("not_applicable", "مصداق ندارد"),
                        ],
                        default="unreviewed",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clause_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_assessments",
                        to="assessments.clauseassessment",
                    ),
                ),
                (
                    "sub_clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="frameworks.subclause",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sub_clause__order", "sub_clause_id"],
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="sub_clause_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="assessments.subclauseassessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="subclauseassessment",
            constraint=models.UniqueConstraint(
                fields=("clause_assessment", "sub_clause"),
                name="uniq_subclause_per_clause_assessment",
            ),
        ),
    ]
