# Generated by Django 5.2.15 on 2026-06-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_populate_sub_clauses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="clause_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="assessments.clauseassessment",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="filename_slug",
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                fields=("clause_assessment", "uploaded_by", "filename_slug"),
                name="uniq_clause_image_slug_per_user",
            ),
        ),
    ]
